
export default [
    {displayString:'スライム', inputString:'suraimu'},
    {displayString:'ゴブリン', inputString:'goburinn'},
    {displayString:'ドラゴン', inputString:'doragonn'},
    {displayString:'ナイト', inputString:'naito'},
    {displayString:'オーク', inputString:'o-ku'},
    {displayString:'ジャイアント', inputString:'zyaiannto'},
    {displayString:'オーガ', inputString:'o-ga'},
    {displayString:'悪魔', inputString:'akuma'},
    {displayString:'天使', inputString:'tennsi'},
    {displayString:'魔法を唱える', inputString:'mahouwotonaeru'},
    {displayString:'冒険者になる', inputString:'boukennsyaninaru'},
    {displayString:'魔法で攻撃する', inputString:'mahoudekougekisuru'},
    {displayString:'伝説の防具', inputString:'dennsetunobougu'},
    {displayString:'伝説の武器', inputString:'dennsetunobuki'},
    {displayString:'エクスプロージョン', inputString:'ekusupuro-zyonn'},
    {displayString:'ランクが上がったようだ', inputString:'rannkugaagattayouda'},
    {displayString:'チームのリーダーになる', inputString:'ti-munori-da-ninaru'},
    {displayString:'負けてたまるか', inputString:'maketetamaruka'},
    {displayString:'魔王をたおす', inputString:'maouwotaosu'},
    {displayString:'勇者がきた', inputString:'yuusyagakita'},
    {displayString:'最初の村でレベル上げ', inputString:'saisyonomuradereberuage'},
    {displayString:'ギルドマスターになる', inputString:'girudomasuta-ninaru'},
    {displayString:'最強の冒険者', inputString:'saikyounoboukennsya'},
    {displayString:'はじまりの村', inputString:'hazimarinomura'},
    {displayString:'進化', inputString:'sinnka'},
    {displayString:'レベルが上がったようだ', inputString:'reberugaagattayouda'},
    {displayString:'聖剣を手に入れた', inputString:'seikennwoteniireta'},
    {displayString:'魔剣を手に入れた', inputString:'makennwoteniireta'},
    {displayString:'スキルを駆使して戦う', inputString:'sukiruwokusisitetatakau'},
    {displayString:'規格外のモンスター', inputString:'kikakugainomonnsuta-'},
    {displayString:'魔法の儀式', inputString:'mahounogisiki'},
    {displayString:'つよいスライム', inputString:'tuyoisuraimu'},
    {displayString:'詠唱する', inputString:'eisyousuru'},
    {displayString:'攻撃をかわす', inputString:'kougekiwokawasu'},
    {displayString:'ユニークスキル', inputString:'yuni-kusukiru'},
    {displayString:'魔法の杖', inputString:'mahounotue'},
    {displayString:'魔王', inputString:'maou'},
    {displayString:'勇者', inputString:'yuusya'},
  ]
  
  